# Generated by Django 4.2.1 on 2023-05-15 17:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_title', models.CharField(max_length=50)),
                ('trip_summery', models.CharField(max_length=2000)),
                ('trail_conditions', models.CharField(blank=True, max_length=2000, null=True)),
                ('planning_info', models.CharField(blank=True, max_length=2000, null=True)),
                ('other_details', models.CharField(blank=True, max_length=2000, null=True)),
                ('date_posted', models.DateField(default=datetime.date.today)),
                ('last_edited', models.DateTimeField(auto_now=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('map_details', models.URLField(blank=True, max_length=300, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
