# Generated by Django 4.2.1 on 2023-05-24 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_image_user_image_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='posts',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
